CREATE DATABASE mscms_user;
CREATE DATABASE mscms_player;
CREATE DATABASE mscms_training;
CREATE DATABASE mscms_medical;
CREATE DATABASE mscms_notification;
CREATE DATABASE mscms_reports;
CREATE DATABASE mscms_wallet;
CREATE DATABASE mscms_payment;
CREATE DATABASE mscms_store;
CREATE DATABASE mscms_ml;

GRANT ALL PRIVILEGES ON DATABASE mscms_user TO embarkx;
GRANT ALL PRIVILEGES ON DATABASE mscms_player TO embarkx;
GRANT ALL PRIVILEGES ON DATABASE mscms_training TO embarkx;
GRANT ALL PRIVILEGES ON DATABASE mscms_medical TO embarkx;
GRANT ALL PRIVILEGES ON DATABASE mscms_notification TO embarkx;
GRANT ALL PRIVILEGES ON DATABASE mscms_reports TO embarkx;
GRANT ALL PRIVILEGES ON DATABASE mscms_wallet TO embarkx;
GRANT ALL PRIVILEGES ON DATABASE mscms_payment TO embarkx;
GRANT ALL PRIVILEGES ON DATABASE mscms_store TO embarkx;
GRANT ALL PRIVILEGES ON DATABASE mscms_ml TO embarkx;
